# -*- coding: utf-8 -*-

CODE = {
    "00": "İşlem Başarılı",
    "00101": "Belirtilen uygulama anahtarı geçersiz",
    "00102": "Güvenlik doğrulaması başarısız",
    "00103": "İşlemi yapabileceğiniz uygun bir pos bulunamadı. İstek parametrelerinizi kontrol ediniz.",
    "00104": "Bin numarası için tanım bulunamadı",
    "00105": "Geçersiz Kart Numarası",
    "00106": "Kart Son Kullanma Tarihi Geçmiş",
    "50500": "Ödeme servisinde hata alındı",
    "50501": "Ödeme servisinden cevap alınamadı",
    "00500": "Sunucuda beklenmeyen hata",
    "00307": "Ödeme sayfasına devam ediniz",
    "00303": "Olası güvenlik saldırısı",
    "00200": "Sipariş numarası için bilgiler bulundu",
    "00404": "Belirtilen sipariş numarası bulunamadı",
    "01": "İptal/İade talebiniz alınmıştır",
    "00107": "Ödeme tutarı formatı hatalı",
    "50502": "Ödeme servisinden hata iletildi",
    "00707": "Belirtilen sipariş zaten iptal edilmiş",
    "00708": "Sadece aynı gün içinde yapılan işlemler iptal edilebilir! . İade servisini kullanınız",
    "00709": "Belirtilen sipariş için iade işlemi yapılmış, bu nedenle iptal edilemez! İade servisini kullanınız",
    "00710": "Belirtilen sipariş için iade etmek istediğiniz tutar, iade edilebilir tutardan büyüktür!",
    "00711": "İade tutarı formatı hatalı",
    "00108": "Taksit sayısı formatı hatalı",
    "20100": "Kredi kartı limitinizi kontrol ediniz",
}
